version: '3'

services:

  myreverse:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./http-confs:/http-confs:ro
    environment:
      - SERVER_NAME=www.website.com # replace with your domain
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_BROTLI=yes
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://app

  app1:
    build: js-app
    restart: always
    environment:
      - NODE_ENV=production

  app2:
    build: js-app
    restart: always
    environment:
      - NODE_ENV=production

  app3:
    build: js-app
    restart: always
    environment:
      - NODE_ENV=production

